### ISSUE TITLE
cookie 用几次就失效了 怎么解决 需要更换账号吗？

### ISSUE THREAD

**Issue by gyssi007** [yinsel/FofaGUI#1]
如题 用几次就失效了，
另外问一下有没有纯PY脚本啊 不需要图形交互界面

**Comment by yinsel** [comment]
OK



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月11日 19:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [yinsel/FofaGUI] cookie 用几次就失效了 怎么解决 需要更换账号吗？ (Issue #1) |

如题 用几次就失效了，
另外问一下有没有纯PY脚本啊 不需要图形交互界面

**Comment by yinsel** [comment]
> 如题 用几次就失效了， 另外问一下有没有纯PY脚本啊 不需要图形交互界面

本想自动获取cookie，但登录要验证码，所以就放弃了，py脚本的话可以加一个！

**Comment by yinsel** [comment]
> 如题 用几次就失效了， 另外问一下有没有纯PY脚本啊 不需要图形交互界面

已加入命令行版本。
